import Link from 'next/link'
import './globals.css'
import type { Metadata } from 'next'
import { Control } from './Control'

export const metadata: Metadata = {
  title: 'crud test',
  description: 'Generated by toucan',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const resp = await fetch(process.env.NEXT_PUBLIC_API_URL + 'topics', { cache: 'no-store' });  // { next: { revalidate: 0 } }
  const topics = await resp.json(); 

  return (
    <html>
      <body>
        <h2><Link href="/">CRUD_TEST_BOARD</Link></h2>
        <h4>Board List ▼</h4>
        <ol style={{border:'1px solid black'}}>
          {topics.map((topics:any)=>{
            return <li key={topics.id}><Link href={`/read/${topics.id}`}>{topics.title}</Link></li>
          })}
        </ol>
        <h4>Board Content ▼</h4>
        <div style={{border:'1px solid black'}}>
        {children}
        </div>
        <h4>Else ▼</h4>
        <Control/>
      </body>
    </html>
  )
}
